# Generated by Django 4.0.6 on 2022-07-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scp_base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SCPEuclid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_object', models.CharField(max_length=255, verbose_name='Название объекта фонда')),
                ('description', models.CharField(max_length=2000, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='media/', verbose_name='Изображение')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='SCPKetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_object', models.CharField(max_length=255, verbose_name='Название объекта фонда')),
                ('description', models.CharField(max_length=2000, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='media/', verbose_name='Изображение')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='SCPThaumiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_object', models.CharField(max_length=255, verbose_name='Название объекта фонда')),
                ('description', models.CharField(max_length=2000, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='media/', verbose_name='Изображение')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
