# Generated by Django 4.0.6 on 2023-02-02 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scp_base', '0002_scpeuclid_scpketter_scpthaumiel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scp',
            options={'ordering': ('title_object',)},
        ),
        migrations.AlterModelOptions(
            name='scpeuclid',
            options={'ordering': ('title_object',)},
        ),
        migrations.AlterModelOptions(
            name='scpketter',
            options={'ordering': ('title_object',)},
        ),
        migrations.AlterModelOptions(
            name='scpthaumiel',
            options={'ordering': ('title_object',)},
        ),
    ]
