# Generated by Django 4.0.6 on 2023-02-03 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='expirations_date',
            field=models.DateField(default=datetime.datetime(2026, 2, 2, 16, 42, 23, 454995), verbose_name='Срок годности'),
        ),
    ]
