# Generated by Django 4.0.6 on 2022-09-20 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_alter_card_expirations_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='expirations_date',
            field=models.DateField(default=datetime.datetime(2025, 9, 19, 21, 4, 54, 804207), verbose_name='Срок годности'),
        ),
    ]
