# Generated by Django 4.0.6 on 2023-02-03 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_alter_card_expirations_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='expirations_date',
            field=models.DateField(default=datetime.datetime(2026, 2, 2, 17, 29, 3, 528143), verbose_name='Срок годности'),
        ),
    ]
