# Generated by Django 4.0.6 on 2023-01-26 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_alter_card_expirations_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='expirations_date',
            field=models.DateField(default=datetime.datetime(2026, 1, 25, 20, 25, 31, 374210), verbose_name='Срок годности'),
        ),
    ]
