# Generated by Django 4.0.6 on 2023-01-30 06:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_alter_card_expirations_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='expirations_date',
            field=models.DateField(default=datetime.datetime(2026, 1, 29, 12, 23, 3, 66451), verbose_name='Срок годности'),
        ),
    ]
