# Generated by Django 4.0.6 on 2023-01-30 08:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_alter_card_expirations_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='expirations_date',
            field=models.DateField(default=datetime.datetime(2026, 1, 29, 14, 5, 18, 349591), verbose_name='Срок годности'),
        ),
    ]
