# Generated by Django 4.0.6 on 2023-02-02 05:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0011_alter_card_expirations_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='expirations_date',
            field=models.DateField(default=datetime.datetime(2026, 2, 1, 11, 58, 6, 963588), verbose_name='Срок годности'),
        ),
    ]
