# Generated by Django 4.0.6 on 2023-02-03 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_message_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='profile',
        ),
    ]
