# Generated by Django 4.1.7 on 2023-03-11 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_remove_message_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Message",
        ),
    ]
